name: Unpack
on: workflow_dispatch
permissions:
  contents: write
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
          unzip -o ./*.zip -x '.github/*'
          rm -f ./*.zip
          git config user.name github-actions
          git config user.email actions@github.com
          git add -A
          git commit -m "Unpack project"
          git push
